language: php
sudo: false
services:
- mysql
cache:
  directories:
  - "$HOME/.composer/cache/files"
matrix:
  fast_finish: true
  include:
  - php: 7.1
env:
- SYMFONY_VERSION="4.0.*" DB=mysql
before-install:
- composer self-update
install:
- cp .env.travis.dist .env
- composer install
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test
notifications:
email: hamza.bedoui@webhelpmedica.com
deploy:
  provider: heroku
  api_key:
    secure: t6xqbLSXLTva06lSifV0Y+YGJI7Xjt3iunb5M3TvLbC1uHK5dlsTbUKVgbeWQwS4Xq92a5cnlWwRO+ZFXTt/Fi325sNelsp+J12pk8lJ1PkKZWzY3VNO0B2LoxDtMqVIW9AEHqp5ivfvwkgcHkAts9FLqLV1KF+wNZYeI5WufBZTiuuSa3ZC3WaOjOcjKLmKOSe1A3S5Rgehrd4my7tpmP2R1pjED6D4jPCAiAv2iC6VBXxNYHQAo2ixNdeHcnQBsvIb4JVn7ERz6lVmi/Bo8zFJkMAwkSDkzJYPxFfQdvMc1JEuPPTfgqU7iaFB9bjV4QtvgM4XtNKE8AmdiEmVtW8Urdrjr1D+vcOIHUe8CoPkhvlE3TMuS21gMHVWl6NNkJLywsaVz1zYQBXuAAE3I0oBLy7t8TAa+FfO+JUz/YhekF0QRZuweLTYQJTcLbdbOq5LLAN+H1fjU8dzvfQT3GV67TI9yPxTh7nm4HFVB/VpfOSUqDjJlZF3kQXWNq9sxjVgGeC55x41A483mKTDcUzULoX8SbgwiGSFFIhIB67NG7Yo86ER1LSr1CAZlVqJzBt52bvVqB9aTSpOvqOaJ/iB4tkDXkPAX3BmQU2bQk3AE9yteYoTtcd85pjf4eF8Tlz9JfpeoF2tJ4CP1N/N8N6sjDkAVzvcpOSA+pdUJwU=
  app: symfony-blog-part-2
